# Generated by Django 3.1.7 on 2021-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210721_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='path',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
