# Generated by Django 3.1.7 on 2021-07-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='path',
        ),
        migrations.CreateModel(
            name='Image_Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=254, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
