# Generated by Django 3.1.7 on 2021-07-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210723_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_path',
            name='image_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
